import type { FunctionalCoreNode, GpuFunctionalModule } from "../functional/compiler.ts";
import { renderFunctionalCompilationTrace } from "../functional/compilation_trace.ts";
import type { FunctionalEvaluationResult } from "../functional/evaluator.ts";
import type { LoweredRustFunctionalProgram } from "./lowering.ts";

export interface RustFunctionalTraceInput {
  readonly title: string;
  readonly source: string;
  readonly lowered: LoweredRustFunctionalProgram;
  readonly compiledModule: GpuFunctionalModule;
  readonly coreNodes: readonly FunctionalCoreNode[];
  readonly evaluation: FunctionalEvaluationResult;
}

export function renderRustFunctionalTrace(input: RustFunctionalTraceInput): string {
  return renderFunctionalCompilationTrace({
    title: input.title,
    sourceLabel: "Rust source",
    introduction:
      "This file is generated by `deno task trace:rust-functional`. The Rust functional profile is\n" +
      "parsed and normalized on the host; name resolution, typechecking, and core lowering happen on the\n" +
      "GPU. Its current execution profile is lazy, so this fixture uses only expressions whose result is\n" +
      "the same under Rust's strict evaluation.",
    source: input.source,
    surface: input.lowered,
    compiledModule: input.compiledModule,
    coreNodes: input.coreNodes,
    evaluation: input.evaluation,
  });
}
