import { renderFunctionalCompilationTrace } from "../functional/compilation_trace.ts";
import type { FunctionalCoreNode, GpuFunctionalModule } from "../functional/compiler.ts";
import type { FunctionalEvaluationResult } from "../functional/evaluator.ts";
import type { LoweredOneSubmlFunctionalProgram } from "./lowering.ts";

export interface OneSubmlFunctionalTraceInput {
  readonly title: string;
  readonly source: string;
  readonly lowered: LoweredOneSubmlFunctionalProgram;
  readonly compiledModule: GpuFunctionalModule;
  readonly coreNodes: readonly FunctionalCoreNode[];
  readonly evaluation: FunctionalEvaluationResult;
}

export function renderOneSubmlFunctionalTrace(input: OneSubmlFunctionalTraceInput): string {
  return renderFunctionalCompilationTrace({
    title: input.title,
    sourceLabel: "1SubML source",
    introduction:
      "This file is generated by `deno task trace:onesubml-functional`. The bounded 1SubML profile is\n" +
      "parsed and structurally normalized on the host; name resolution, rank-1 generalization,\n" +
      "predicative rank-2 checking, and core lowering happen on the GPU before WebAssembly execution.",
    source: input.source,
    surface: input.lowered,
    compiledModule: input.compiledModule,
    coreNodes: input.coreNodes,
    evaluation: input.evaluation,
  });
}
