import { renderCompilationTrace } from "../functional/compilation_trace.ts";
import type { CoreNode, GpuModule } from "../functional/compiler.ts";
import type { WasmExecution } from "../functional/wasm_execution.ts";
import type { LoweredGleamProgram } from "./frontend.ts";

export interface GleamTraceInput {
  readonly title: string;
  readonly source: string;
  readonly lowered: LoweredGleamProgram;
  readonly compiledModule: GpuModule;
  readonly coreNodes: readonly CoreNode[];
  readonly evaluation: WasmExecution;
}

export function renderGleamTrace(input: GleamTraceInput): string {
  return renderCompilationTrace({
    title: input.title,
    sourceLabel: "Gleam source modules",
    introduction:
      "This file is generated by `deno task trace:gleam`. Gleam syntax is parsed and\n" +
      "desugared on the host, modules are joined through typed artifacts, and name resolution,\n" +
      "Hindley–Milner inference, typechecking, and core lowering run on the GPU.",
    source: input.source,
    surface: {
      definitions: input.lowered.modules.flatMap((module) => module.definitions),
      typeDeclarations: input.lowered.modules.flatMap((module) => module.typeDeclarations),
      module: input.lowered.module,
    },
    compiledModule: input.compiledModule,
    coreNodes: input.coreNodes,
    evaluation: input.evaluation,
  });
}
