export {
  type EncodedFunctionalDefinitionType,
  type EncodedFunctionalModule,
  type EncodedFunctionalTypeDeclaration,
  FUNCTIONAL_CONSTRUCTOR_BYTE_LENGTH,
  FUNCTIONAL_CONSTRUCTOR_WORD_LENGTH,
  FUNCTIONAL_CORE_V1_PRIMITIVE_CAPABILITIES,
  FUNCTIONAL_DEFINITION_BYTE_LENGTH,
  FUNCTIONAL_DEFINITION_WORD_LENGTH,
  FUNCTIONAL_MAXIMUM_CONSTRUCTOR_ARITY,
  FUNCTIONAL_MAXIMUM_EXPRESSION_NODES,
  FUNCTIONAL_MAXIMUM_SOURCE_BYTE_LENGTH,
  FUNCTIONAL_MODULE_ABI_VERSION,
  FUNCTIONAL_NO_INDEX,
  FUNCTIONAL_NODE_BYTE_LENGTH,
  FUNCTIONAL_NODE_WORD_LENGTH,
  FUNCTIONAL_PAIR_CONSTRUCTOR_NAME,
  FUNCTIONAL_TYPE_BYTE_LENGTH,
  FUNCTIONAL_TYPE_WORD_LENGTH,
  FUNCTIONAL_UNIT_CONSTRUCTOR_NAME,
  FunctionalAlgebraicTypeWord,
  FunctionalBinaryOperator,
  FunctionalConstructorWord,
  FunctionalCoreTag,
  FunctionalDefinitionWord,
  type FunctionalDiagnostic,
  type FunctionalDiagnosticCode,
  FunctionalEvaluationProfile,
  FunctionalExpressionTag,
  FunctionalNodeWord,
  FunctionalPrimitiveCapability,
  type FunctionalSourceType,
  type FunctionalSpan,
  type FunctionalType,
  FunctionalTypecheckingProfile,
  type FunctionalTypeDeclaration,
  type FunctionalTypeSchema,
  FunctionalUnaryOperator,
} from "./src/functional/abi.ts";
export {
  type FunctionalCompilationOptions,
  type FunctionalCompileResult,
  type FunctionalCoreNode,
  GpuFunctionalCompiler,
  type GpuFunctionalModule,
} from "./src/functional/compiler.ts";
export {
  type FunctionalBatchEvaluationOptions,
  type FunctionalDeepBatchEvaluationOptions,
  type FunctionalDeepEvaluationOptions,
  type FunctionalDeepEvaluationResult,
  type FunctionalDeepValue,
  type FunctionalEvaluationOptions,
  type FunctionalEvaluationResult,
  type FunctionalEvaluationStats,
  type FunctionalInputValue,
  type FunctionalRuntimeFault,
  type FunctionalValue,
  GpuFunctionalEvaluator,
} from "./src/functional/evaluator.ts";
export {
  type TypeCoreCapabilityEvidence,
  type TypeCoreCapabilityGoal,
  type TypeCoreCapabilityPattern,
  type TypeCoreCapabilityPremise,
  type TypeCoreCapabilityResolution,
  type TypeCoreCapabilityResolutionOptions,
  type TypeCoreCapabilityRule,
  type TypeCoreCapabilityTypePattern,
  type TypeCoreCapabilityVerification,
  type TypeCoreCapabilityWitness,
} from "./src/functional/capability_contract.ts";
export { TypeCoreCapabilityResolver } from "./src/functional/capability_resolver.ts";
export {
  type TypeCoreExecutionOptions,
  type TypeCoreExecutionResult,
  type TypeCoreExpression,
  type TypeCoreFunction,
  type TypeCoreFunctionParameter,
  TypeCoreKind,
  type TypeCoreMatchArm,
  type TypeCorePattern,
  type TypeCoreProgram,
  type TypeCoreType,
  type TypeCoreTypeConstructor,
  type TypeCoreTypeExpression,
  type TypeCoreTypePattern,
  type TypeCoreValue,
} from "./src/functional/type_core_contract.ts";
export { GpuTypeCoreExecutor } from "./src/functional/type_core.ts";
export { requestWebGpuDevice } from "./src/webgpu.ts";
