import { renderFunctionalCompilationTrace } from "../functional/compilation_trace.ts";
import type { FunctionalCoreNode, GpuFunctionalModule } from "../functional/compiler.ts";
import type { FunctionalEvaluationResult } from "../functional/evaluator.ts";
import type { LoweredGleamFunctionalProgram } from "./frontend.ts";

export interface GleamFunctionalTraceInput {
  readonly title: string;
  readonly source: string;
  readonly lowered: LoweredGleamFunctionalProgram;
  readonly compiledModule: GpuFunctionalModule;
  readonly coreNodes: readonly FunctionalCoreNode[];
  readonly evaluation: FunctionalEvaluationResult;
}

export function renderGleamFunctionalTrace(input: GleamFunctionalTraceInput): string {
  return renderFunctionalCompilationTrace({
    title: input.title,
    sourceLabel: "Gleam source modules",
    introduction:
      "This file is generated by `deno task trace:gleam-functional`. Gleam syntax is parsed and\n" +
      "desugared on the host, modules are joined through typed artifacts, and name resolution,\n" +
      "Hindley–Milner inference, typechecking, and core lowering run on the GPU.",
    source: input.source,
    surface: {
      definitions: input.lowered.modules.flatMap((module) => module.definitions),
      typeDeclarations: input.lowered.modules.flatMap((module) => module.typeDeclarations),
      module: input.lowered.module,
    },
    compiledModule: input.compiledModule,
    coreNodes: input.coreNodes,
    evaluation: input.evaluation,
  });
}
