/**
 * Builds the browser playground into `playground/dist`.
 *
 * `deno bundle` compiles the whole compiler for the browser, so the playground needs no npm
 * dependency, bundler config, or framework. The previous playground carried React, Vite, Babel, and
 * 258 MB of `node_modules` to do the same job.
 */
const root = new URL("../", import.meta.url);
const out = new URL("dist/", import.meta.url);

async function copy(from: URL, to: string): Promise<number> {
  const bytes = await Deno.readFile(from);
  await Deno.writeFile(new URL(to, out), bytes);
  return bytes.byteLength;
}

await Deno.remove(out, { recursive: true }).catch(() => {});
await Deno.mkdir(out, { recursive: true });

// Examples are inlined so the page needs no fetch waterfall to become interactive. Only top-level
// files are taken: `kernel/` is the multi-module sample, and the page has one textarea.
const exampleDirectory = new URL("examples/gleam/", root);
const names: string[] = [];
for await (const entry of Deno.readDir(exampleDirectory)) {
  if (entry.isFile && entry.name.endsWith(".gleam")) names.push(entry.name);
}
names.sort();
const examples = await Promise.all(names.map(async (name) => ({
  name: name.replace(/\.gleam$/, "").replaceAll("_", " ").replaceAll("-", " "),
  source: await Deno.readTextFile(new URL(name, exampleDirectory)),
})));

/**
 * A deliberately large module, generated rather than checked in.
 *
 * Every hand-written example is between 118 and 669 bytes, and at that size the page measures
 * almost nothing but the one GPU readback — which is why the playground has always looked slow. This
 * gives the pipeline enough nodes that per-node cost is visible instead of buried under a fixed
 * ~11 ms floor.
 *
 * It is synthetic, and the page says so. The shapes are the expensive ones from BASELINE — recursion,
 * constructor plus `case`, and polymorphic instantiation — but a generator cannot reproduce how real
 * code distributes them. `deno task bench:gleam-stdlib` against the actual Gleam standard library is
 * the measurement to trust; this is the one that fits in a tab.
 */
function stressModule(groups: number): string {
  const parts: string[] = [
    "// Generated by playground/build.ts. Synthetic, but large enough that the page stops",
    "// measuring the GPU readback floor and starts measuring the compiler.",
    "",
    "pub type Shape {",
    "  Circle(radius: Int)",
    "  Rect(width: Int, height: Int)",
    "  Point",
    "}",
    "",
  ];
  for (let group = 0; group < groups; group++) {
    parts.push(
      `fn area${group}(shape) {`,
      "  case shape {",
      `    Circle(radius: r) -> 3 * r * r`,
      `    Rect(width: w, height: h) -> w * h + ${group}`,
      "    Point -> 0",
      "  }",
      "}",
      "",
      `fn total${group}(n, acc) {`,
      "  case n <= 0 {",
      "    True -> acc",
      `    False -> total${group}(n - 1, acc + n)`,
      "  }",
      "}",
      "",
      `fn larger${group}(left, right) {`,
      `  case area${group}(left) > area${group}(right) {`,
      "    True -> left",
      "    False -> right",
      "  }",
      "}",
      "",
      `fn score${group}(seed) {`,
      `  let shape = larger${group}(Circle(radius: seed), Rect(width: seed, height: ${group + 1}))`,
      `  total${group}(area${group}(shape) % 24, 0)`,
      "}",
      "",
    );
  }
  const sum = Array.from({ length: groups }, (_, group) => `score${group}(${group % 9 + 1})`);
  parts.push("pub fn main() -> Int {", `  ${sum.join(" + ")}`, "}", "");
  return parts.join("\n");
}

// Not written into `examples/gleam/`: the directory scan above would pick it up on the next build
// and the page would list it twice.
examples.push({ name: "stress (generated, large)", source: stressModule(120) });

await Deno.writeTextFile(new URL("examples.json", out), JSON.stringify(examples));

/**
 * Two entry points, not one. The frontend worker has to be a separate bundle so `new Worker` has a
 * URL to fetch; bundling it into `main.js` would leave nothing to load.
 */
for (const entry of ["main", "frontend_worker"]) {
  const bundle = new Deno.Command(Deno.execPath(), {
    args: [
      "bundle",
      "--platform",
      "browser",
      "--minify",
      "--output",
      new URL(`${entry}.js`, out).pathname,
      new URL(`${entry}.ts`, import.meta.url).pathname,
    ],
    stdout: "inherit",
    stderr: "inherit",
  }).outputSync();
  if (!bundle.success) throw new Error(`deno bundle failed for ${entry}.ts`);
}

const parserBytes = await copy(
  new URL("language/gleam/generated/wasm/parser.wasm", root),
  "parser.wasm",
);
await copy(new URL("language/gleam/generated/wasm/parser.plan", root), "parser.plan");
await copy(new URL("index.html", import.meta.url), "index.html");
await copy(new URL("styles.css", import.meta.url), "styles.css");

const bundleBytes = (await Deno.stat(new URL("main.js", out))).size;
const workerBytes = (await Deno.stat(new URL("frontend_worker.js", out))).size;
console.log(
  `playground/dist: ${examples.length} examples, bundle ${(bundleBytes / 1024).toFixed(0)}KB, ` +
    `worker ${(workerBytes / 1024).toFixed(0)}KB, parser ${(parserBytes / 1024).toFixed(0)}KB`,
);
