/**
 * Loads `gleam-lang/stdlib` as a module set with an entry that roots every public function.
 *
 * The entry matters more than it looks. Lowering prunes to what the entry reaches, so a small `main`
 * leaves gpufuck compiling a handful of nodes while `gleam build` compiles the whole library — an
 * earlier version of the stdlib benchmark lowered 252 KB of Gleam to 66 surface nodes and the
 * comparison meant nothing. Binding all 353 exports keeps the corpus whole.
 *
 * Shared by the benchmark and the frame profiler because it was previously generated by hand outside
 * the repository, which made both unreproducible by anyone else.
 *
 * @module
 */
import type { GleamSourceModule } from "../gleam.ts";

/** The nineteen source modules this frontend accepts, in the order BASELINE recorded them. */
export const GLEAM_STDLIB_MODULES = [
  "bit_array",
  "bool",
  "bytes_tree",
  "dict",
  "dynamic",
  "dynamic/decode",
  "float",
  "function",
  "int",
  "io",
  "list",
  "option",
  "order",
  "pair",
  "result",
  "set",
  "string",
  "string_tree",
  "uri",
] as const;

function exportedFunctions(source: string): readonly string[] {
  const names: string[] = [];
  for (const match of source.matchAll(/^pub fn ([a-z_][a-z0-9_]*)\s*\(/gm)) names.push(match[1]!);
  return names;
}

/**
 * An entry binding every public function in `sources`.
 *
 * Names are prefixed rather than discarded: a `_`-prefixed binding is read as a discard pattern by
 * this frontend and the whole thing fails to lower.
 */
export function allExportsEntry(sources: readonly GleamSourceModule[]): GleamSourceModule {
  const imports: string[] = [];
  const bindings: string[] = [];
  for (const module of sources) {
    const alias = module.name.replaceAll("/", "_");
    imports.push(`import ${module.name} as ${alias}`);
    for (const name of exportedFunctions(module.source)) {
      bindings.push(`  let keep_${alias}_${name} = ${alias}.${name}`);
    }
  }
  return {
    name: "stdlib_entry",
    source: `${imports.join("\n")}\n\npub fn main() {\n${bindings.join("\n")}\n  Nil\n}\n`,
  };
}

export interface GleamStdlibCorpus {
  /** The library's own modules, without the synthesised entry. */
  readonly sources: readonly GleamSourceModule[];
  readonly entry: GleamSourceModule;
  /** Sources plus entry, ready for `lowerGleamSources`. */
  readonly all: readonly GleamSourceModule[];
  readonly sourceBytes: number;
}

export async function readGleamStdlib(checkout: string): Promise<GleamStdlibCorpus> {
  const sources: GleamSourceModule[] = await Promise.all(
    GLEAM_STDLIB_MODULES.map(async (name) => ({
      name: `gleam/${name}`,
      source: await Deno.readTextFile(`${checkout}/src/gleam/${name}.gleam`),
    })),
  );
  const entry = allExportsEntry(sources);
  const all = [...sources, entry];
  return {
    sources,
    entry,
    all,
    sourceBytes: all.reduce(
      (total, module) => total + new TextEncoder().encode(module.source).byteLength,
      0,
    ),
  };
}
