import { renderFunctionalCompilationTrace } from "../functional/compilation_trace.ts";
import type { FunctionalCoreNode, GpuFunctionalModule } from "../functional/compiler.ts";
import type { FunctionalEvaluationResult } from "../functional/evaluator.ts";
import type { LoweredOcamlFunctionalProgram } from "./lowering.ts";

export interface OcamlFunctionalTraceInput {
  readonly title: string;
  readonly source: string;
  readonly lowered: LoweredOcamlFunctionalProgram;
  readonly compiledModule: GpuFunctionalModule;
  readonly coreNodes: readonly FunctionalCoreNode[];
  readonly evaluation: FunctionalEvaluationResult;
}

export function renderOcamlFunctionalTrace(input: OcamlFunctionalTraceInput): string {
  return renderFunctionalCompilationTrace({
    title: input.title,
    sourceLabel: "OCaml source",
    introduction:
      "This file is generated by `deno task trace:ocaml-functional`. The bounded OCaml profile is\n" +
      "parsed and normalized on the host; name resolution, Hindley–Milner inference, typechecking, and\n" +
      "core lowering happen on the GPU. The fixtures use pure, total expressions because the current\n" +
      "functional evaluation profile is lazy while OCaml evaluation is strict.",
    source: input.source,
    surface: input.lowered,
    compiledModule: input.compiledModule,
    coreNodes: input.coreNodes,
    evaluation: input.evaluation,
  });
}
