import { renderFunctionalCompilationTrace } from "../functional/compilation_trace.ts";
import type { FunctionalCoreNode, GpuFunctionalModule } from "../functional/compiler.ts";
import type { FunctionalEvaluationResult } from "../functional/evaluator.ts";
import type { LoweredHaskellFunctionalProgram } from "./lowering.ts";

export interface HaskellFunctionalTraceInput {
  readonly title: string;
  readonly source: string;
  readonly lowered: LoweredHaskellFunctionalProgram;
  readonly compiledModule: GpuFunctionalModule;
  readonly coreNodes: readonly FunctionalCoreNode[];
  readonly evaluation: FunctionalEvaluationResult;
}

export function renderHaskellFunctionalTrace(input: HaskellFunctionalTraceInput): string {
  return renderFunctionalCompilationTrace({
    title: input.title,
    sourceLabel: "Haskell source",
    introduction:
      "This file is generated by `deno task trace:haskell-functional`. The bounded Haskell profile is\n" +
      "parsed and normalized on the host; name resolution, Hindley–Milner inference, typechecking, and\n" +
      "core lowering happen on the GPU. Source definitions without signatures remain unannotated in the\n" +
      "functional ABI and are inferred there.",
    source: input.source,
    surface: input.lowered,
    compiledModule: input.compiledModule,
    coreNodes: input.coreNodes,
    evaluation: input.evaluation,
  });
}
